#
# Copyright (C) 2026 The Android Open Source Project
# Copyright (C) 2026 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

# Inherit from those products. Most specific first.
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)

# Inherit some common TWRP stuff.
$(call inherit-product, vendor/twrp/config/common.mk)

# Inherit from PD2183 device
$(call inherit-product, device/vivo/PD2183/device.mk)

PRODUCT_DEVICE := PD2183
PRODUCT_NAME := twrp_PD2183
PRODUCT_BRAND := vivo
PRODUCT_MODEL := V2183A
PRODUCT_MANUFACTURER := vivo

PRODUCT_GMS_CLIENTID_BASE := android-vivo

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRIVATE_BUILD_DESC="vext_k6983v1_64-user 12 SP1A.210812.003 compiler260420142447 release-keys"

BUILD_FINGERPRINT := vivo/PD2183/PD2183:12/SP1A.210812.003/compiler260420142447:user/release-keys

# Recovery root files (init scripts, MTK utils)
# NOTE: modules.load.recovery is auto-generated by BOARD_RECOVERY_KERNEL_MODULES
# NOTE: .ko files are handled by BOARD_RECOVERY_KERNEL_MODULES in BoardConfig.mk
# NOTE: Use literal device/vivo/PD2183 path — $(DEVICE_PATH) is not available in product mk context
RECOVERY_ROOT_FILES := \
    device/vivo/PD2183/recovery/root/init.recovery.mt6983.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.mt6983.rc \
    device/vivo/PD2183/recovery/root/init.recovery.platform.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.platform.rc \
    device/vivo/PD2183/recovery/root/init.recovery.svc.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.svc.rc \
    device/vivo/PD2183/recovery/root/init.recovery.service.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.service.rc \
    device/vivo/PD2183/recovery/root/init.recovery.touch.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.touch.rc \
    device/vivo/PD2183/recovery/root/init.recovery.usb.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.usb.rc \
    device/vivo/PD2183/recovery/root/init.recovery.hlthchrg.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.hlthchrg.rc \
    device/vivo/PD2183/recovery/root/init.recovery.ldconfig.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.ldconfig.rc \
    device/vivo/PD2183/recovery/root/mtk-plpath-utils.rc:$(TARGET_COPY_OUT_RECOVERY)/root/mtk-plpath-utils.rc \
    device/vivo/PD2183/recovery/root/servicemanager.recovery.rc:$(TARGET_COPY_OUT_RECOVERY)/root/servicemanager.recovery.rc

PRODUCT_COPY_FILES += $(RECOVERY_ROOT_FILES)
